### PR TITLE
Naming change for consistency [GOL-108]

### PR DESCRIPTION
**Pull request by salva-abate**
This branch is dedicated solely to chaning the naming conevntion of graph objects to keep them consistent throughout. Node is now vertex, connection is now edge and IO is now port.

### CODE REVIEW

**Comment by jboolean** [comment]
This code does not run. Suggest closing the PR and re-submitting a working version.

**Comment by RobertWarrenGilmore** [comment]
I agree with @jboolean. I will review this once it builds.

**Comment by RobertWarrenGilmore** [comment]
As for identifying the problem, look into the recent merge of the automatic layout engine into develop. That still has the old names.

**Comment by RobertWarrenGilmore** [comment]
(That's in lib/layout and in test/test-layout.js.)

**Pull request closed without merging**
